swaylock \
	--image /home/branchmanager/Downloads/images/stormlighttest.jpg \
	--clock \
	--indicator \
	--indicator-radius 100 \
	--indicator-thickness 7 \
	--effect-blur 7x5 \
	--effect-vignette 0.5:0.5 \
	--ring-color bb00cc \
	--key-hl-color ca9ee6 \
	--line-color ca9ee6 \
	--inside-color 232634 \
	--separator-color 00000000 \
	--grace 2 \
	--font 'Ubuntu Nerd Font'\
	--fade-in 1.1 \
	 --text-color 8caaee \
	 -f
