format = """
[](#1e2030)\
$username\
[](bg:#363a4f fg:#1e2030)\
$directory\
[](fg:#363a4f bg:#6e738d)\
$git_branch\
$git_status\
[](fg:#6e738d bg:#b7bdf8)\
$c\
$elixir\
$elm\
$golang\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
[](fg:#b7bdf8 bg:#8aadf4)\
$docker_context\
[](fg:#8aadf4 bg:#7dc4e4)\
$time\
[ ](fg:#7dc4e4)\
"""

# Disable the blank line at the start of the prompt
# add_newline = false

# You can also replace your username with a neat symbol like  to save some space
[username]
show_always = true
style_user = "bg:#1e2030"
style_root = "bg:#1e2030"
format = '[$user ]($style)'

[directory]
style = "bg:#363a4f"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = " "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = "  "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important  " = "  "

[c]
symbol = " "
style = "bg:#b7bdf8"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = " "
style = "bg:#8aadf4"
format = '[ $symbol $context ]($style) $path'

[elixir]
symbol = " "
style = "bg:#b7bdf8"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = " "
style = "bg:#b7bdf8"
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = ""
style = "bg:#6e738d"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#6e738d"
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = " "
style = "bg:#b7bdf8"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = " "
style = "bg:#b7bdf8"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "bg:#b7bdf8"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = " "
style = "bg:#b7bdf8"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "bg:#b7bdf8"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = " "
style = "bg:#b7bdf8"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
style = "bg:#b7bdf8"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#7dc4e4"
format = '[  $time ]($style)'
