swaylock \
	--image /home/noah/Pictures/fox.jpg
	--indicator-radius 100 \
	--indicator-thickness 7 \
	--ring-color bb00cc \
	--key-hl-color ca9ee6 \
	--line-color ca9ee6 \
	--inside-color 232634 \
	--separator-color 00000000 \
	--font 'Ubuntu Nerd Font'\
	 --text-color 8caaee
