#! /bin/sh

#LOCATION ON MY MACHINE: /home/branchmanager/.config/bspwm
#keep in mind the rc file for schkd,is in ~/.config/sxhkd/
sxhkd &

nitrogen --restore

xrandr --output DisplayPort-0 --primary --mode 3440x1440 --pos 3840x720 --rotate normal --output DisplayPort-1 --mode 3840x2160 --pos 0x0 --rotate normal --output DisplayPort-2 --off --output HDMI-A-0 --off

#Execute these scripts on launch
/home/branchmanager/launch_scripts/polybar_launch.sh &

/home/branchmanager/launch_scripts/picom_launch.sh | tee 2>&1 /home/branchmanager/.Dotfiles/logs/picom.log &

bspc monitor  DisplayPort-0 -d 6 7 8 9 10
bspc monitor  DisplayPort-1 -d 1 2 3 4 5 # I II III IV V VI VII VIII IX X

bspc config border_width         0
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

xsetroot -cursor_name left_ptr

nitrogen --restore
